-- CRIAR TABELAS
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOME VARCHAR2(255) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    EMAIL VARCHAR2(255),
    SALARIO_BRUTO NUMBER(9,2) NOT NULL,
    SALARIO_LIQUIDO NUMBER(9,2),
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY(ID_FUNCIONARIO)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    NOME VARCHAR2(255) NOT NULL,
    SIGLA VARCHAR2(10) NOT NULL,
    CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY(ID_DEPARTAMENTO)
);